# Generated by Django 4.1.1 on 2022-09-15 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone_destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='pizza_company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='drone_destination.pizzacompany'),
            preserve_default=False,
        ),
    ]
