# Generated by Django 4.1.1 on 2022-09-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_destination', '0003_delivery_delivery_complete_delivery_delivery_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='location_of_last_request',
        ),
        migrations.AddField(
            model_name='drone',
            name='gps_lat',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drone',
            name='gps_long',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
